# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95e1e8f996f461e7bafe3a942a20ef3588646fbae4d7fc54b0944c4d3115b5b3b95576e5743ba2e208faba07f7ffe3f8854ebf5015588020e3ebbe80f2733b6a

test:
  secret_key_base: d2610f371b9be44962564538886c0183bd31fbc4cdd968cb3795de26eb76cb26e9d753ebca9021507d0e79ea71ce4dd33cbd312f5c7798cdbd1527c3e97f71c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
